### ISSUE TITLE
Add LIRC support through the LircOutputPin.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#106]
```
Add LIRC support through the LircOutputPin.\r\n\r\nMust follow all LIRC 
interface standards.\r\nMore implementation details to come as they are known.
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 18 Apr 2013 at 7:07

**Comment by octavian-paraschiv** [comment]
Does not seem to work any more with build 3.0.56

**Comment by octavian-paraschiv** [comment]
There are no known use cases involving LircOutputPin. 
Pushing issue to release 3.1.x.

**Comment by octavian-paraschiv** [comment]
RCC service is planned to be dropped because its usage is extremely low. Consequently LIRC support is also dropped.
