### ISSUE TITLE
Open file dialogs cannot cope with UNC paths typed in file name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#110]
```
Open file dialogs cannot cope with UNC paths typed in file name then press 
Enter key.\r\n\r\nMost Windows programs can handle this scenario.
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 18 Apr 2013 at 7:07

**Comment by octavian-paraschiv** [comment]
Failed regression tests with build 3.0.56
Some folders are shown with empty contents when using UNC paths.

**Comment by octavian-paraschiv** [comment]
[Relates to Issue #218]

**Comment by octavian-paraschiv** [comment]
QA passed with build 3.0.60, needs end user confirmation
