### ISSUE TITLE
Bookmarks can become non-editable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#131]
```
1. Select a file in playlist having the bookmark manager closed
2. Open the bookmark manager
3. Click on the first bookmark. It does not enter in edit mode.
4. Now all other bookmarks (per this file or other) are non-editable.


```

Original issue reported on code.google.com by `octavian...@gmail.com` on 24 Apr 2013 at 10:02

**Comment by octavian-paraschiv** [comment]
Reproduced again with build 3.0.56.
Sequence: 
- launch a ProTONE Player
- make sure it starts with an empty play list
- add several mp3 files that have bookmarks,
-- confirm their bookmarks can be edited (bookmarks page)
- add some Deezer items to the playlist
-- confirm the bookmarks of the mp3 files can still be edited
- play one Deezer item

=> After this step the bookmarks of the mp3 files can no longer be edited; player restart is required to edit them again

**Comment by octavian-paraschiv** [comment]
QA passed with build 3.0.60, needs end user confirmation
