### ISSUE TITLE
Upgrade from 1.8 to 1.9 results in an unusable application due to registry settings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#140]
```
On a system that does not have ProTONE Suite install version 1.8.40.
Then upgrade to latest 1.9.47.
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 13 May 2013 at 11:37

**Comment by octavian-paraschiv** [comment]
When doing regression tests make this issue does not happen when upgrading from an earlier version to latest. Supported earlier versions are those in the "legacy" folder int he FTP site. 

When this comment was written (June 11th, 2018) these were:
- 1.8.40
- 1.9.90
- 1.10.31
- 2.0.44
- 2.1.42
- 2.2.17
