### ISSUE TITLE
Media Library: Category names in property grid - media library (with multiple files selected) don't get translated after language is changed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#200]
```
Media Library: Category names in property grid - media library (with multiple 
files selected) don't get translated after language is changed
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 23 Sep 2014 at 11:24

**Comment by octavian-paraschiv** [comment]
Is is impossible to change Category names in property grid, other than at startup. This behavior will be present for ever or until redesigned to use other controls than property grids.
