### ISSUE TITLE
Redesign the main player window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#208]
```
Redesign the main player window - see attached file
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 15 Jan 2015 at 1:40

Attachments:
* [ProTONE Suite GUI v.2.1.png](https://storage.googleapis.com/google-code-attachments/protone-suite/issue-208/comment-0/ProTONE Suite GUI v.2.1.png)

**Comment by octavian-paraschiv** [comment]
Verified with build 2.1.24
