### ISSUE TITLE
Allow external applications to gather signal analisys data from ProTONE Player

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#210]
```
Expose data via a WCF interface. 
Restrict connections only to local machine.
=> WCF over net pipe
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 22 Jan 2015 at 1:37

**Comment by octavian-paraschiv** [comment]
Verified with build 2.1.24

**Comment by octavian-paraschiv** [comment]
Needs to be verified separately. If not working it should be handled in release 3.1.x

**Comment by octavian-paraschiv** [comment]
Verified with build 3.0.56, works ok
