### ISSUE TITLE
Adding artwork images results in non-playable media

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#74]
```
"After I add an artwork image to a MP3, this one can no longer be played.\r\nA 
rendering exception is returned:\r\n\r\nA runtime error has occured in the 
application. Details: \r\n\r\nNo combination of filters could be found to 
render the stream.\r\n\r\n\r\nAfter I remove the image the MP3 is playable 
again."
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 18 Apr 2013 at 7:07

**Comment by octavian-paraschiv** [comment]
Now, the saved media is always playable but the error thrown in case that the selected image is too large is not user friendly. It just says "property not valid". The message should clearly indicate the max. allowed size of the selected image (file size / dimensions ...)

**Comment by octavian-paraschiv** [comment]
The rework effort is larger than initially estimated. 
Resolution is pushed to release 3.1.x

**Comment by octavian-paraschiv** [comment]
Will NOT be fixed. Cost vs. benefits would be too disadvantageous.
