### ISSUE TITLE
Some context menu entries in Media Library are not getting translated as language is changed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [octavian-paraschiv/protone-suite#97]
```
Some context menu entries in Media Library are not getting translated as 
language is changed\r\n\r\n
```

Original issue reported on code.google.com by `octavian...@gmail.com` on 18 Apr 2013 at 7:07

**Comment by octavian-paraschiv** [comment]
Still happens with build 3.0.56 - seen in Catalog Explorer context menu
![image](https://user-images.githubusercontent.com/12813700/41838304-bae7266c-7868-11e8-9af1-080a9fff7b23.png)

**Comment by octavian-paraschiv** [comment]
QA passed with build 3.0.60, needs end user confirmation
